### ISSUE TITLE
Can you include "deploy" instructions into your readme?

### ISSUE THREAD

**Issue by blairanderson** [salihozdemir/stackoverflow-clone#3]
So far this clone looks beautiful. Best way to get a lot of tips/fixes/etc. would be to include a vercel "deploy" link or deploy instructions for vercel.

**Comment by salihozdemir** [comment]
![image](https://user-images.githubusercontent.com/41580619/91773154-e67e4480-ebee-11ea-9f55-89f2e5d6acf1.png)

I didin't create Heroku deploy button due to the above reason. I hope readme has been more useful now.
